services:
  - type: web
    name: traffic-analysis
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: USE_MODELS
        value: "true"
      - key: BASE_DIR
        value: /app
      - key: PORT
        value: 10000
      - key: CAMERA_URL_TEMPLATE
        value: https://giaothong.hochiminhcity.gov.vn:8007/Render/CameraHandler.ashx?id={camera_id}
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: "true"
      - key: TF_MEMORY_ALLOCATION
        value: "512MB"
    buildCommand: "echo 'Build completed'"